version: '3.8'

services:
  # SQL Server instance for logs
  log-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=SuperSecret7!
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data-logs:/var/opt/mssql
    networks:
      - app-network

  # RabbitMQ instance
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user123
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5673:5672"   # RabbitMQ broker port
      - "15673:15672" 
    networks:
      - app-network


  # MonitoringAPI - scaled to 2 replicas for X-axis scaling
  monitoring-api:
    build:
      context: .
      dockerfile: MonitoringAPI/Dockerfile
    ports:
      - "49152:80"
    depends_on:
      - rabbitmq
    networks:
      - app-network
   # deploy:
    #  replicas: 2  
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user123
      - RABBITMQ_PASS=123456

  # LoggingService - scaled to 2 replicas for X-axis scaling
  logging-service:
    build:
      context: .
      dockerfile: LoggingService/Dockerfile
    depends_on:
      - rabbitmq
      - log-db
    networks:
      - app-network
    deploy:
      replicas: 2  
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=user123
      - RABBITMQ_PASS=123456
      - DB_HOST=log-db
      - DB_USER=sa
      - DB_PASS=SuperSecret7!

volumes:
  mssql-data-logs:

networks:
  app-network:
    driver: bridge
